name: tv_plus_example
description: "Demonstrates how to use the tv_plus plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  tv_plus:
    path: ../

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0
  flutter_pre_commit: ^0.2.4

flutter:
  generate: true
  uses-material-design: true
